### ISSUE TITLE
After deployment, the workflow was created incorrectly

### ISSUE THREAD

**Issue by liuzhiyuan0502** [apache/linkis#4167]
Let me ask you a question：After deployment, the workflow was created incorrectly.
Error Message: 
Warning code: 50032，Warning message: Try to ask Linkis forcreating a new contextld failed Linkis error msg:HttpClientResultException:errCode: 10905desc.URL/api/rest_j/v1/contextservice/createContextlDrequestfailed!1ResponseBodyfmethod":"/api/rest_j/1/contextservice/createConSupplied VIP Address cannot be null","data":[data":null. errCode: 10905 ,desc: URL/api/rest_j/v1/contextservice/createContextlDrequestfailed!ResponseBodyIsmethod":"/api/rest j/1/contextservice/createConSupplied VIP Address cannot be null","data".data"null.,ip: dss-service ,port: 9003serviceKinddss-framework-orchestrator-dss-service ,port: 9003server-devip:serviceKind.dss-framework-orchestrator-server-dev.

_Originally posted by @15259236303 in https://github.com/apache/linkis/discussions/3944#discussioncomment-4553764_

**Comment by binbinCheng** [comment]
Hello! You failed to create ContextID. It is recommended to check whether the parameters are correct when creating

**Comment by QuantumXiecao** [comment]
This problem is due to linkis-gateway-server-support-1.1.1.jar  version incompatible as depicted by the following picture:

![image](https://user-images.githubusercontent.com/99702568/217999409-fdeca619-f798-4969-b05b-3367ea560f7f.png)

So Eureka could not extract services by the ps-cs(Actually should be LINKIS-PS-PUBLICSERVICE)

![image](https://user-images.githubusercontent.com/99702568/217999683-5f38a3e7-5f6e-4d66-b2d5-57345173f761.png)

**Comment by QuantumXiecao** [comment]
Of course this problem in essence is due to the released linkis has duplicate jars(url:http://mirrors.obs.cn-north-276.intelligentmininglab.com/apache/linkis/apache-linkis-1.3.0-incubating-bin.tar.gz):
![image](https://user-images.githubusercontent.com/99702568/218007174-9c264d95-e20e-4977-a216-dcd73802773a.png)

Users who download this linkis tar might encounter the same problem.
Strongly recommend redistribute one new 1.3.0 release jar as quickly as possible.
@binbinCheng @peacewong

**Comment by liuzhiyuan0502** [comment]
Thank you very much for your guidance!

**Comment by casionone** [comment]
> 
Thanks! 
Already published binary packages cannot be re-covered
This has been fixed in version 1.3.1

**Comment by casionone** [comment]
I will close this issue. You can reopen if necessary
